In [1]:
import numpy as np


In [3]:
#dodjeljujemo input vrijednosti
input_value=np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [8]:
#dodjeljujemo output vrijednosti
output=np.array([[0],[1],[1],[0]])
output.shape

(4, 1)

In [10]:
#dodjeljujemo tezine
weights=np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [11]:
#dodajemo bias
bias=0.3

In [12]:
#aktivacijska funkcija - sigmoid
def sigmoid_func(x):
  return 1/(1+np.exp(-x))

In [13]:
#nalazimo izvod ove funkcije koji ce nam koristiti kod opadajuceg gradijenta
def der(x):
  return sigmoid_func(x)*(1-sigmoid_func(x))

In [16]:
#epoch - broj prolaza cjelokupnog skupa podataka za obuku koji je algoritam zavrsio
for epochs in range(1000):
  input_arr=input_value
  
  weighted_sum=np.dot(input_arr, weights)+bias  #vektorski proizvod inputa i tezina + bias
  first_output=sigmoid_func(weighted_sum) 
  error=first_output-output
  total_error=np.square(np.subtract(first_output,output)).mean() #srednji kvadrat
  #print(total_error)

  first_der=error
  second_der=der(first_output)  #izvodi za gradient descent algorithm 
  derivative=first_der*second_der

  t_input=input_value.T  #input vrijednosti su transponovane, shape je bio (4,2), a sada je (2,4)
  final_derivative=np.dot(t_input,derivative)

  #update weights
  weights=weights-0.5*final_derivative  #0.5 je learning rate koju smo setovali

  #update bias
  for i in derivative:
    bias=bias-0.5*i

print(weights)
print(bias)


[[-0.4197366]
 [ 8.9923745]]
[-4.19869816]


In [19]:
#predictions
pred=np.array([0,1]) #provjeravamo predvidjanje za niz ciji je target value jednak 1 (definisali na pocetku)
#zelimo da provjerimo koliko se predvidjanje razlikuje od 1
result=np.dot(pred, weights)+bias
res=sigmoid_func(result)

print(res)
#dobijamo broj priblizan jedinici

[0.0097718]
